Custom SSH port
MichaelSims/gerrit-slack-bot pull request #17
Opened 2018-01-13 17:59 UTC by djarosz

- ability to use non default ssh port
- bot username is optional in slack notification as
  if no username is given Incommit WebHook configuration will be used

2018-01-15 22:00 UTC, MichaelSims commented
Hi, thank you for the pull requests! Just wanted to say that I've got my hands a bit full but will be taking a look in the next day or so. Thanks again.

2018-01-21 19:55 UTC, MichaelSims requested changes
Hi! Thanks much for the pull request. There are some tweaks I'd like to see made.

In addition to the inline comments I left, I'd like to see the change to make the Slack username optional be its own separate commit. I intend to keep a clean linear history (rebasing instead of merging), and since that change doesn't seem related at all to custom SSH ports, I'd like to see it separated out.

I am more than happy to make these tweaks myself, but figured I'd give you right of first refusal.

2018-01-21 19:55 UTC, MichaelSims commented on app/src/dist/config.yaml
> +# Incoming WebHook URL - required
Capitalizing is fine, but why the change to CamelCase?

2018-01-21 19:55 UTC, MichaelSims commented on app/src/dist/config.yaml
> +# See https://api.slack.com/incoming-webhooks fro details
"for" is misspelled

2018-01-21 19:55 UTC, MichaelSims commented on app/src/dist/config.yaml
> +# - username: if null or empty Incomming WebHook configured user name will be used
"Incoming" misspelled

2018-01-21 19:55 UTC, MichaelSims commented on app/src/dist/config.yaml
> +# - iconUrl: if null or empty Incomming WebHook configured user icon will be used
Spelling again

2018-01-21 19:55 UTC, MichaelSims commented on tests/src/test/resources/sims/michael/gerritslackbot/config.yaml
> +# See https://api.slack.com/incoming-webhooks fro details
Since the comments in this file are a copy/paste from the dist version, the same comments I made above apply.

2018-01-21 21:08 UTC, djarosz commented
Thanks for Your comments. I see Your point  on clean commit history and please feel free to make changes Yourself. I won't be able to do them my self till next week any way.

2018-01-21 22:14 UTC, MichaelSims commented
I've reorganized the commits a bit and tweaked some of the minor things like spelling, and pushed to master. I kept you as the author of these commits since the work was yours and I was just tweaking. I hope that is OK.

2018-01-21 22:14 UTC, closed without merging